In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
master_df = pd.read_csv("factor1and2.csv")
master_df = master_df.drop(master_df.columns[0], axis = 1)
master_df["ticker"] = master_df["ticker"].str[2:-1]
master_df

,permno,yyyymm,monthid,ticker,conm,gvkey,cusip,naics,gsubind,IM,range_20,log_vol_dollar_20,range_120,log_vol_dollar_120,xret_5,xret_10,xret_20,xret_indsize_20,xret_indsize_std20,xret_40,xret_120,xret_indsize_120,xret_indsize_std120,KDJ_20,deviation_pct20,MoneyFlowIndex_20,RSI_20,KDJ_120,deviation_pct120,MoneyFlowIndex_120,RSI_120,IV_capm,mdr,ami_3,beta_3y,beta_5y,tail_2y,dp,leverage,BL,roe,roa,profitability,sales_g_q,sales_g_ttm,op_income_g_q,ni_g_q,op_income_g_ttm,ni_g_ttm,sue_NI,BM,AM,EP,SP,roe_q,roa_q,Cto,pe_ttm,lag_log_size,PRC,VOL,RET,SHROUT,ret_f1,ret_f2,ret_f3,ret_f4,ret_f5,ret_f6,ret_f7,ret_f8,ret_f9,ret_f10,ret_f11,ret_f12,Sue,abr
0,76868.0,199102.0,134.0,AAON,b'AAON INC',b'021542',000360206,b'333415',b'20102010',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,-9.547739e-02,32.541727,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.934687,0.328125,737.0,0.050000,22150.0,-0.190476,0.117647,-0.105263,-0.058824,-0.187500,0.307692,0.117647,-0.052632,0.166667,-0.095238,0.263158,-0.166667,NaN,4.0
1,76868.0,199103.0,135.0,AAON,b'AAON INC',b'021542',000360206,b'333415',b'20102010',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,1.324833e-16,100.000000,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.983477,0.265625,2610.0,-0.190476,22150.0,0.117647,-0.105263,-0.058824,-0.187500,0.307692,0.117647,-0.052632,0.166667,-0.095238,0.263158,-0.166667,0.050000,NaN,4.0
2,76868.0,199104.0,136.0,AAON,b'AAON INC',b'021542',000360206,b'333415',b'20102010',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,-1.628788e-01,85.830960,33.333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.772168,0.296875,2941.0,0.117647,22150.0,-0.105263,-0.058824,-0.187500,0.307692,0.117647,-0.052632,0.166667,-0.095238,0.263158,-0.166667,0.050000,-0.047619,NaN,4.0
3,76868.0,199105.0,137.0,AAON,b'AAON INC',b'021542',000360206,b'333415',b'20102010',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,5.555556e-02,92.495079,66.666667,0.500000,-0.041195,73.311513,50.000000,NaN,NaN,NaN,NaN,NaN,-1.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.883393,0.265625,980.0,-0.105263,22150.0,-0.058824,-0.187500,0.307692,0.117647,-0.052632,0.166667,-0.095238,0.263158,-0.166667,0.050000,-0.047619,0.050000,NaN,4.0
4,76868.0,199106.0,138.0,AAON,b'AAON INC',b'021542',000360206,b'333415',b'20102010',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,-5.116279e-02,100.000000,100.000000,0.500000,-0.125311,72.023491,43.478261,NaN,NaN,NaN,NaN,NaN,-1.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.772168,0.250000,796.0,-0.058824,22150.0,-0.187500,0.307692,0.117647,-0.052632,0.166667,-0.095238,0.263158,-0.166667,0.050000,-0.047619,0.050000,-0.142857,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402602,14642.0,201908.0,476.0,LPG,b'DORIAN LPG LTD',b'317264',Y2106R110,b'483111',b'10102040',0.029088,0.031203,15.225946,0.037272,14.275330,-0.007484,-0.030100,0.016553,0.002967,0.024611,0.126121,0.548214,0.535484,0.026109,0.304266,-2.979536e-02,60.957570,52.964427,0.482868,0.204489,63.257321,60.095137,0.022111,0.075741,-6.688773e-07,1.266981,1.170917,-1.000000,0.0,0.388910,1.780870,-0.055820,-0.031344,0.041383,-0.115278,-0.008469,-0.002570,-0.007193,-0.001025,-0.017594,-2.269988,2.576947,4.589209,-0.143845,0.453206,-0.017202,-0.009613,0.021153,200.000000,6.224137,10.390000,118914.0,0.135519,55064.0,-0.002887,0.201737,0.152610,0.078746,-0.152455,-0.152439,-0.216727,0.089552,-0.133825,-0.058394,0.103359,-0.011710,0.344193,NaN
402603,14642.0,201909.0,477.0,LPG,b'DORIAN LPG LTD',b'317264',Y2106R110,b'483111',b'10102040',-0.068947,0.047185,15.313383,0.039738,14.600066,0.050549,0.096540,0.186116,0.215624,0.026693,0.172150,0.699747,0.699538,0.027900,0.514681,9.155854e-02,70.420965,64.855072,0.483769,0.256893,63.722975,60.733216,0.027622,0.070915,1.528799e-06,1.137767,1.125406,-1.000000,0.0,0.381463,1.761659,-0.026411,-0.014992,0.061897,1.184248,0.306370,0.019372,0.015679,0.025608,0.005898,2.069755,1.846969,3.253730,-0.048781,0.389885,0.006656,0.003738,0.038015,200.000000,6.349340,10.360000,73485.0,-0.002887,55064.0,0.201737,0.152610,0.078746,-0.152455,-0.152439,-0.216727,0.089552,-0.133825,-0.058394,0.103359,-0.011710,-0.050948,0.344193,NaN
402604,14642.0,201910.0,478.0,LPG,b'DORIAN LPG LTD',b'317264',Y2106R110,b'483111',b'10102040',-0.036589,0.037277,15.118410,0.039079,14.832281,-0.023304,0.004580,-0.017946,-0.033683,0.020431,0.168170,0.305536,0.283684,0.026614,0.587298,-1.972844e-02,60.615797,49.529781,0.478457,0.155960,61.880269,54.862053,0.016127,0.025472,6.751113e-08,1.149805,1.101305,0.269824,0.0,0.381463,1.761659,-0.026411,-0.014992,0.061897,1.184248,0.306370,0.019372,0.015679,0.025608,0.005898,2.069755,1.846969,3.253730,-0.048781,0.389885,0.006656,0.003738,0.038015,200.000000,6.346448,12.450000,114185.0,0.201737,54596.0,0.152610,0.078746,-0.152455,-0.152439,-0.216727,0.089552,-0.133825,-0.058394,0.103359,-0.011710,-0.050948,0.023720,1.385321,NaN
402605,14642.0,201911.0,479.0,LPG,b'DORIAN LPG LTD',b'317264',Y2106R110,b'483111',b'10102040',-0.063401,0.035880,15.583060,0.039225,15.111992,-0.001414,0.009136,0.140249,0.108927,0.017993,0.142412,0.552287,0.510356,0.025937,0.503751,4.538394e-02,73.360570,76.092545,0.488628,0.286556,66.974326,60.884500,0.017961,0.049904,7.212713e-07,1.149106,1.189946,-1.000000,0.0,0.366813,1.720724,0.025792,0.014989,0.090163,1.221124,0.582507,0.028476,0.029115,0.051448,0.032865,2.217067,1.672978,2.878733,0.043149,0.428703,0.044296,0.025145,0.056784,23.175423,6.522560,14.350000,90335.0,0.152610,54596.0,0.078746,-0.152455,-0.152439,-0.216727,0.089552,-0.133825,-0.058394,0.103359,-0.011710,-0.050948,0.023720,0.332927,1.385321,NaN
402606,14642.0,201912.0,480.0,LPG,b'DORIAN LPG LTD',b'317264',Y2106R110,b'483111',b'10102040',0.072172,0.033055,15.538577,0.036685,15.306292,0.013805,0.123661,0.108359,0.146520,0.016443,0.248608,0.537454,0.489424,0.022143,0.647353,8.220211e-02,81.667758,74.869110,0.514025,0.352253,70.066834,64.665757,0.017831,0.034428,6.394846e-07,1.071830,1.251013,-1.000000,0.0,0.366813,1.720724,0.025792,0.014989,0.090163,1.221124,0.582507,0.028476,0.029115,0.051448,0.032865,2.217067,1.672978,2.878733,0.043149,0.428703,0.044296,0.025145,0.056784,23.175423,6.663711,15.480000,97202.0,0.078746,54596.0,-0.152455,-0.152439,-0.216727,0.089552,-0.133825,-0.058394,0.103359,-0.011710,-0.050948,0.023720,0.332927,0.115279,1.385321,NaN

# Revisions in Analyst Earnings Forecasts

In [3]:
meanest = pd.read_csv("meanest.csv")
meanest["monthid"] = 12*(meanest["STATPERS"].str[0:4].astype(float) - 1980) + meanest["STATPERS"].str[5:7].astype(float)
meanest

       oftic TICKER    STATPERS MEASURE  FPI  MEANEST  monthid
0         KN   001J  2014-03-20     EPS    1     2.15    411.0
1         KN   001J  2014-04-17     EPS    1     2.04    412.0
2         KN   001J  2014-05-15     EPS    1     1.75    413.0
3         KN   001J  2014-06-19     EPS    1     1.75    414.0
4         KN   001J  2014-07-17     EPS    1     1.75    415.0
...      ...    ...         ...     ...  ...      ...      ...
596324     Y   YML1  2023-12-14     EPS    1     2.58    528.0
596325     Y   YML1  2024-01-18     EPS    1     2.58    529.0
596326   PPG   YPG1  2006-06-15     EPS    1    -0.03    318.0
596327   PPG   YPG1  2006-07-20     EPS    1    -0.03    319.0
596328   CMI   YZM1  2014-04-17     EPS    1     0.08    412.0

[596329 rows x 7 columns]

In [4]:
price = pd.read_csv("a3_price.csv")
price["monthid"] = 12*(price["STATPERS"].str[0:4].astype(float) - 1980) + price["STATPERS"].str[5:7].astype(float)
price

       oftic TICKER    STATPERS MEASURE  PRICE  monthid
0         KN   001J  2014-03-20     EPS  32.01    411.0
1         KN   001J  2014-04-17     EPS  29.99    412.0
2         KN   001J  2014-05-15     EPS  30.08    413.0
3         KN   001J  2014-06-19     EPS  31.38    414.0
4         KN   001J  2014-07-17     EPS  29.15    415.0
...      ...    ...         ...     ...    ...      ...
598271     Y   YML1  2023-12-14     EPS  10.96    528.0
598272     Y   YML1  2024-01-18     EPS  11.04    529.0
598273   PPG   YPG1  2006-06-15     EPS   1.11    318.0
598274   PPG   YPG1  2006-07-20     EPS   1.26    319.0
598275   CMI   YZM1  2014-04-17     EPS   1.50    412.0

[598276 rows x 6 columns]

In [5]:
merged_info = pd.merge(meanest, price[["oftic","TICKER", "monthid", "PRICE"]], on=["oftic", "TICKER", "monthid"], how="inner")
merged_info

       oftic TICKER    STATPERS MEASURE  FPI  MEANEST  monthid  PRICE
0         KN   001J  2014-03-20     EPS    1     2.15    411.0  32.01
1         KN   001J  2014-04-17     EPS    1     2.04    412.0  29.99
2         KN   001J  2014-05-15     EPS    1     1.75    413.0  30.08
3         KN   001J  2014-06-19     EPS    1     1.75    414.0  31.38
4         KN   001J  2014-07-17     EPS    1     1.75    415.0  29.15
...      ...    ...         ...     ...  ...      ...      ...    ...
596023     Y   YML1  2023-12-14     EPS    1     2.58    528.0  10.96
596024     Y   YML1  2024-01-18     EPS    1     2.58    529.0  11.04
596025   PPG   YPG1  2006-06-15     EPS    1    -0.03    318.0   1.11
596026   PPG   YPG1  2006-07-20     EPS    1    -0.03    319.0   1.26
596027   CMI   YZM1  2014-04-17     EPS    1     0.08    412.0   1.50

[596028 rows x 8 columns]

In [6]:
groups = merged_info.groupby(["oftic", "TICKER"])

res = []

for i, group in groups:
    tmp = (group["MEANEST"] - group["MEANEST"].shift(1))/group["PRICE"].shift(1)
    res = res + (list(tmp.rolling(6).sum()))
    
    
merged_info["Re"] = pd.Series(res)
merged_info

,oftic,TICKER,STATPERS,MEASURE,FPI,MEANEST,monthid,PRICE,Re
0,KN,001J,2014-03-20,EPS,1,2.15,411.0,32.01,NaN
1,KN,001J,2014-04-17,EPS,1,2.04,412.0,29.99,NaN
2,KN,001J,2014-05-15,EPS,1,1.75,413.0,30.08,NaN
3,KN,001J,2014-06-19,EPS,1,1.75,414.0,31.38,NaN
4,KN,001J,2014-07-17,EPS,1,1.75,415.0,29.15,NaN
...,...,...,...,...,...,...,...,...,...
596023,Y,YML1,2023-12-14,EPS,1,2.58,528.0,10.96,-0.004134
596024,Y,YML1,2024-01-18,EPS,1,2.58,529.0,11.04,-0.004716
596025,PPG,YPG1,2006-06-15,EPS,1,-0.03,318.0,1.11,-0.004243
596026,PPG,YPG1,2006-07-20,EPS,1,-0.03,319.0,1.26,-0.004243
596027,CMI,YZM1,2014-04-17,EPS,1,0.08,412.0,1.50,-0.004243

In [7]:
tickers = []
monthids = []
Res = []

groups = merged_info.groupby(['oftic', "monthid"])

for (tic,moid), group in groups:
    tickers.append(tic)
    monthids.append(moid)
    Res.append(group["Re"].mean())
    
    
newdf = pd.DataFrame(data = {
    "ticker" : tickers,
    "monthid" : monthids,
    "Res" : Res,
})

master_df = pd.merge(master_df, newdf, on = ["ticker", "monthid"], how="left")
master_df

,permno,yyyymm,monthid,ticker,conm,gvkey,cusip,naics,gsubind,IM,range_20,log_vol_dollar_20,range_120,log_vol_dollar_120,xret_5,xret_10,xret_20,xret_indsize_20,xret_indsize_std20,xret_40,xret_120,xret_indsize_120,xret_indsize_std120,KDJ_20,deviation_pct20,MoneyFlowIndex_20,RSI_20,KDJ_120,deviation_pct120,MoneyFlowIndex_120,RSI_120,IV_capm,mdr,ami_3,beta_3y,beta_5y,tail_2y,dp,leverage,BL,roe,roa,profitability,sales_g_q,sales_g_ttm,op_income_g_q,ni_g_q,op_income_g_ttm,ni_g_ttm,sue_NI,BM,AM,EP,SP,roe_q,roa_q,Cto,pe_ttm,lag_log_size,PRC,VOL,RET,SHROUT,ret_f1,ret_f2,ret_f3,ret_f4,ret_f5,ret_f6,ret_f7,ret_f8,ret_f9,ret_f10,ret_f11,ret_f12,Sue,abr,Res
0,76868.0,199102.0,134.0,AAON,b'AAON INC',b'021542',000360206,b'333415',b'20102010',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,-9.547739e-02,32.541727,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.934687,0.328125,737.0,0.050000,22150.0,-0.190476,0.117647,-0.105263,-0.058824,-0.187500,0.307692,0.117647,-0.052632,0.166667,-0.095238,0.263158,-0.166667,NaN,4.0,NaN
1,76868.0,199103.0,135.0,AAON,b'AAON INC',b'021542',000360206,b'333415',b'20102010',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,1.324833e-16,100.000000,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.983477,0.265625,2610.0,-0.190476,22150.0,0.117647,-0.105263,-0.058824,-0.187500,0.307692,0.117647,-0.052632,0.166667,-0.095238,0.263158,-0.166667,0.050000,NaN,4.0,NaN
2,76868.0,199104.0,136.0,AAON,b'AAON INC',b'021542',000360206,b'333415',b'20102010',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,-1.628788e-01,85.830960,33.333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.772168,0.296875,2941.0,0.117647,22150.0,-0.105263,-0.058824,-0.187500,0.307692,0.117647,-0.052632,0.166667,-0.095238,0.263158,-0.166667,0.050000,-0.047619,NaN,4.0,NaN
3,76868.0,199105.0,137.0,AAON,b'AAON INC',b'021542',000360206,b'333415',b'20102010',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,5.555556e-02,92.495079,66.666667,0.500000,-0.041195,73.311513,50.000000,NaN,NaN,NaN,NaN,NaN,-1.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.883393,0.265625,980.0,-0.105263,22150.0,-0.058824,-0.187500,0.307692,0.117647,-0.052632,0.166667,-0.095238,0.263158,-0.166667,0.050000,-0.047619,0.050000,NaN,4.0,NaN
4,76868.0,199106.0,138.0,AAON,b'AAON INC',b'021542',000360206,b'333415',b'20102010',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,-5.116279e-02,100.000000,100.000000,0.500000,-0.125311,72.023491,43.478261,NaN,NaN,NaN,NaN,NaN,-1.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.772168,0.250000,796.0,-0.058824,22150.0,-0.187500,0.307692,0.117647,-0.052632,0.166667,-0.095238,0.263158,-0.166667,0.050000,-0.047619,0.050000,-0.142857,NaN,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402602,14642.0,201908.0,476.0,LPG,b'DORIAN LPG LTD',b'317264',Y2106R110,b'483111',b'10102040',0.029088,0.031203,15.225946,0.037272,14.275330,-0.007484,-0.030100,0.016553,0.002967,0.024611,0.126121,0.548214,0.535484,0.026109,0.304266,-2.979536e-02,60.957570,52.964427,0.482868,0.204489,63.257321,60.095137,0.022111,0.075741,-6.688773e-07,1.266981,1.170917,-1.000000,0.0,0.388910,1.780870,-0.055820,-0.031344,0.041383,-0.115278,-0.008469,-0.002570,-0.007193,-0.001025,-0.017594,-2.269988,2.576947,4.589209,-0.143845,0.453206,-0.017202,-0.009613,0.021153,200.000000,6.224137,10.390000,118914.0,0.135519,55064.0,-0.002887,0.201737,0.152610,0.078746,-0.152455,-0.152439,-0.216727,0.089552,-0.133825,-0.058394,0.103359,-0.011710,0.344193,NaN,0.054879
402603,14642.0,201909.0,477.0,LPG,b'DORIAN LPG LTD',b'317264',Y2106R110,b'483111',b'10102040',-0.068947,0.047185,15.313383,0.039738,14.600066,0.050549,0.096540,0.186116,0.215624,0.026693,0.172150,0.699747,0.699538,0.027900,0.514681,9.155854e-02,70.420965,64.855072,0.483769,0.256893,63.722975,60.733216,0.027622,0.070915,1.528799e-06,1.137767,1.125406,-1.000000,0.0,0.381463,1.761659,-0.026411,-0.014992,0.061897,1.184248,0.306370,0.019372,0.015679,0.025608,0.005898,2.069755,1.846969,3.253730,-0.048781,0.389885,0.006656,0.003738,0.038015,200.000000,6.349340,10.360000,73485.0,-0.002887,55064.0,0.201737,0.152610,0.078746,-0.152455,-0.152439,-0.216727,0.089552,-0.133825,-0.058394,0.103359,-0.011710,-0.050948,0.344193,NaN,0.007823
402604,14642.0,201910.0,478.0,LPG,b'DORIAN LPG LTD',b'317264',Y2106R110,b'483111',b'10102040',-0.036589,0.037277,15.118410,0.039079,14.832281,-0.023304,0.004580,-0.017946,-0.033683,0.020431,0.168170,0.305536,0.283684,0.026614,0.587298,-1.972844e-02,60.615797,49.529781,0.478457,0.155960,61.880269,54.862053,0.016127,0.025472,6.751113e-08,1.149805,1.101305,0.269824,0.0,0.381463,1.761659,-0.026411,-0.014992,0.061897,1.184248,0.306370,0.019372,0.015679,0.025608,0.005898,2.069755,1.846969,3.253730,-0.048781,0.389885,0.006656,0.003738,0.038015,200.000000,6.346448,12.450000,114185.0,0.201737,54596.0,0.152610,0.078746,-0.152455,-0.152439,-0.216727,0.089552,-0.133825,-0.058394,0.103359,-0.011710,-0.050948,0.023720,1.385321,NaN,-0.002021
402605,14642.0,201911.0,479.0,LPG,b'DORIAN LPG LTD',b'317264',Y2106R110,b'483111',b'10102040',-0.063401,0.035880,15.583060,0.039225,15.111992,-0.001414,0.009136,0.140249,0.108927,0.017993,0.142412,0.552287,0.510356,0.025937,0.503751,4.538394e-02,73.360570,76.092545,0.488628,0.286556,66.974326,60.884500,0.017961,0.049904,7.212713e-07,1.149106,1.189946,-1.000000,0.0,0.366813,1.720724,0.025792,0.014989,0.090163,1.221124,0.582507,0.028476,0.029115,0.051448,0.032865,2.217067,1.672978,2.878733,0.043149,0.428703,0.044296,0.025145,0.056784,23.175423,6.522560,14.350000,90335.0,0.152610,54596.0,0.078746,-0.152455,-0.152439,-0.216727,0.089552,-0.133825,-0.058394,0.103359,-0.011710,-0.050948,0.023720,0.332927,1.385321,NaN,-0.004380
402606,14642.0,201912.0,480.0,LPG,b'DORIAN LPG LTD',b'317264',Y2106R110,b'483111',b'10102040',0.072172,0.033055,15.538577,0.036685,15.306292,0.013805,0.123661,0.108359,0.146520,0.016443,0.248608,0.537454,0.489424,0.022143,0.647353,8.220211e-02,81.667758,74.869110,0.514025,0.352253,70.066834,64.665757,0.017831,0.034428,6.394846e-07,1.071830,1.251013,-1.000000,0.0,0.366813,1.720724,0.025792,0.014989,0.090163,1.221124,0.582507,0.028476,0.029115,0.051448,0.032865,2.217067,1.672978,2.878733,0.043149,0.428703,0.044296,0.025145,0.056784,23.175423,6.663711,15.480000,97202.0,0.078746,54596.0,-0.152455,-0.152439,-0.216727,0.089552,-0.133825,-0.058394,0.103359,-0.011710,-0.050948,0.023720,0.332927,0.115279,1.385321,NaN,-0.009547

In [16]:
master_df = master_df.sort_values(by = ['cusip', 'monthid']).reset_index(drop=True)
groups = master_df.groupby("cusip")

R6s = []
R11s = []

for i, group in groups:
    past6 = list(group["RET"].rolling(6).sum().shift(2))
    past11 = list(group["RET"].rolling(11).sum().shift(2))
    R6s = R6s + past6
    R11s = R11s + past11
    
master_df["R6"] = pd.Series(R6s)
master_df["R11"] = pd.Series(R11s)
master_df

402607
402607
402607

In [19]:
master_df.to_csv("factorsA1_to_A5.csv")